Repository CESARBR/knot-cloud-sdk-js-amqp, pull requests merged in 2020-04, with the labels that each got.

#2 Bootstrap project
  .babelrc
  .eslintignore
  .eslintrc
  gulpfile.js
  package.json
  src/index.js
  yarn.lock
Labels: enhancement, good first issue, priority: medium

#4 fix: remove gulp from dev dependencies
  gulpfile.js
  package.json
  yarn.lock
Labels: good first issue, priority: medium

#5 Add rollup js bundler
  package.json
  rollup.config.js
  yarn.lock
Labels: enhancement, priority: low

#6 release: Bump to v1.0.0
  .npmignore
  CHANGELOG.md
  package.json
Labels: enhancement, priority: medium

#9 release: Bump version to v1.0.1
  CHANGELOG.md
  package.json
Labels: priority: medium, release

#8 Add "once" method
  src/Client.js
Labels: enhancement, priority: low
