Repository CESARBR/knot-cloud-sdk-js-amqp, pull requests merged in 2020-05, with the labels that each got.

#11 Add README.md file
  README.md
Labels: documentation, priority: medium

#14 Add reply_to property
  src/Client.js
Labels: bug, priority: medium

#15 Improve SDK with unsubscribe method
  src/Client.js
Labels: enhancement, priority: medium
